MACRO(MACRO_CMAKE_VERSION_CHECKS)

message(STATUS "cmake version: ${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}")

if (NOT "${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS "2.8")
      cmake_policy(SET CMP0009 NEW) # suppress FOLLOW_SYMLINKS warning for GLOB_RECURSE
endif ()


ENDMACRO(MACRO_CMAKE_VERSION_CHECKS)
